packages:
  - apps/*
  - services/*
  - infrastructure/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - cpu-features
  - esbuild
  - prisma
  - protobufjs
  - ssh2
